# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_creation_devis', models.DateTimeField(auto_now_add=True)),
                ('date_de_modification', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Devis', 'Devis'), ('Facture', 'Facture')], default='Devis', max_length=15)),
                ('date_de_creation_facture', models.DateTimeField()),
                ('etat', models.CharField(choices=[('Pay\xe9s', 'Pay\xe9s'), ('Relance', 'Relance'), ('En attente', 'En attente')], default='En attente', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturier.Client')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDeCommande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturier.Devis')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='produits')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='lignedecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturier.Produit'),
        ),
    ]
