# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='produits')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quotation_creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Quotation', 'Quotation'), ('Bill', 'Bill')], default='Quotation', max_length=15)),
                ('Bill_creation_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Paid', 'PayPaid\xe9s'), ('Revive', 'Revive'), ('Waiting', 'Waiting')], default='Waiting', max_length=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturier.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='devis',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lignedecommande',
            name='devis',
        ),
        migrations.RemoveField(
            model_name='lignedecommande',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Devis',
        ),
        migrations.DeleteModel(
            name='LigneDeCommande',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
        migrations.AddField(
            model_name='commandline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturier.Product'),
        ),
        migrations.AddField(
            model_name='commandline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturier.Quotation'),
        ),
    ]
