# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0002_auto_20181004_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='product'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('PAIEMENT', 'PayPaid\xe9s'), ('REVIVE', 'Revive'), ('WAITING', 'Waiting')], default='WAITING', max_length=15),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='type',
            field=models.CharField(choices=[('QUOTATION', 'Quotation'), ('BILL', 'Bill')], default='QUOTATION', max_length=15),
        ),
    ]
