# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 09:21
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0005_auto_20181004_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Bill_creation_date',
            new_name='bill_creation_date',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Quotation_creation_date',
            new_name='quotation_creation_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cover',
            field=models.ImageField(blank=True, upload_to='customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique_with=('last_name', 'first_name')),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=30)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('PAIEMENT', 'Paid'), ('REVIVE', 'Revive'), ('WAITING', 'Waiting')], default='WAITING', max_length=15),
        ),
    ]
