# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 09:26
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0006_auto_20181005_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=30)),
        ),
    ]
