# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 12:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0007_auto_20181005_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='full_name', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='bill_creation_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
