# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0008_auto_20181008_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='bill_creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
