# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0010_auto_20181008_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandline',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('REVIVE', 'Revive'), ('WAITING', 'En attente')], default='WAITING', max_length=15),
        ),
    ]
